# Generated by Django 5.2.8 on 2025-12-01 15:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Sitio / Identificador')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección Completa')),
                ('encargado', models.CharField(blank=True, max_length=100, verbose_name='Encargado / Manager')),
                ('tipo', models.CharField(blank=True, help_text='Ej: Apto, Bodega', max_length=50, verbose_name='Tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Destino / Sitio',
                'verbose_name_plural': 'Destinos / Sitios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código Único')),
                ('nombre', models.CharField(max_length=200, verbose_name='Descripción / Nombre')),
                ('categoria', models.CharField(choices=[('Kitchen', 'Kitchen'), ('Livingroom', 'Living Room'), ('Bedroom', 'Bedroom'), ('Bathroom', 'Bathroom'), ('Maintenance', 'Maintenance / Tools'), ('Other', 'Other')], max_length=50, verbose_name='Zona de Uso')),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo ($)')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Venta ($)')),
                ('stock_total_global', models.IntegerField(default=0, editable=False, verbose_name='Stock Total (Global)')),
                ('stock_minimo', models.IntegerField(default=5, verbose_name='Stock Mínimo (Reorden)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Empresa / Proveedor')),
                ('contacto', models.CharField(blank=True, max_length=100, verbose_name='Persona de Contacto')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección Física')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('IN', 'Entry (Purchase/Income)'), ('OUT', 'Exit (Usage/Sale)'), ('TRANSFER', 'Transfer (Between Sites)'), ('ADJ_POS', 'Adjustment (+)'), ('ADJ_NEG', 'Adjustment (-)')], max_length=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('referencia', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('razon_ajuste', models.TextField(blank=True, null=True)),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_entrada', to='Inventario.destino', verbose_name='Hacia (Destino)')),
                ('origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_salida', to='Inventario.destino', verbose_name='Desde (Origen)')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.producto')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventario.proveedor'),
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_sitio', to='Inventario.destino')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='Inventario.producto')),
            ],
            options={
                'verbose_name': 'Inventario por Sitio',
                'verbose_name_plural': 'Inventario por Sitios',
                'unique_together': {('producto', 'ubicacion')},
            },
        ),
    ]
